# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    env:
      Solution_Name: Files\Extensions\powerFLC.ExplorerExtension.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      #Test_Project_Path: your-test-project-path                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      #Wap_Project_Directory: your-wap-project-directory-name    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      #Wap_Project_Path: your-wap-project-path                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.
      Configuration: Release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      
      - name: Build the Vault 2022 solution
        run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform=Vault2022 /p:RunWixToolsOutofProc=true
        
      - name: Build the Vault 2021 solution
        run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform=Vault2021 /p:RunWixToolsOutofProc=true
      
      - name: Build the Vault 2020 solution
        run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform=Vault2020 /p:RunWixToolsOutofProc=true
      
      - name: Build the Vault 2019 solution
        run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform=Vault2019 /p:RunWixToolsOutofProc=true
        
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: MSIX Package
          path: Files\Extensions\bin\**\*.msi
      
      - name: Automatic Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.msi
          
